//
// Copyright 2025 Qwerex
//

#ifndef DINING_PHILOSOPHERS_INCLUDE_PHILOSOPHERSTATUS_H_
#define DINING_PHILOSOPHERS_INCLUDE_PHILOSOPHERSTATUS_H_

enum class PhilosopherStatus {
  kThinking,
  kEating,
  kWaiting,
};

#endif  // DINING_PHILOSOPHERS_INCLUDE_PHILOSOPHERSTATUS_H_
